version: '3.7'
#
services:
  irissvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fxdemo
    restart: always
    command: --check-caps false
    hostname: myiris
    
    ports:
    # superserver default port 
    - "51776:1972"
    # webserver/management portal port
    - "52776:52773"
    
    environment:
    - TZ=JST-9
